"""empty message

Revision ID: 6fb0c7376e2e
Revises: f041caacd68e
Create Date: 2024-02-01 09:33:59.119093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb0c7376e2e'
down_revision = 'f041caacd68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_de_billets', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('methode_paiement', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('commentaire', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('commentaire')
        batch_op.drop_column('methode_paiement')
        batch_op.drop_column('nombre_de_billets')

    # ### end Alembic commands ###
