"""empty message

Revision ID: b60d5ce6ed5e
Revises: 3fc41a493434
Create Date: 2024-01-30 19:28:00.868663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60d5ce6ed5e'
down_revision = '3fc41a493434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_image', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billets', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('destination_image')

    # ### end Alembic commands ###
